version: "3.9"

services:
  mysql:
    image: mysql:8.4
    container_name: starbooks-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: starbooks
      MYSQL_USER: starbooks
      MYSQL_PASSWORD: starbooks
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
